name: Gradle Build
on:
    workflow_dispatch:   # 支持手动触发工作流
    push:
        branches:
            - main      # 在 main 分支有 push 操作时触发
    pull_request:
        branches:
            - main      # 在主分支的 pull request 时触发

jobs:
    build:
        runs-on: ubuntu-latest  # 选择运行环境

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2  # 检出代码

            -   name: Set up JDK 21
                uses: actions/setup-java@v2
                with:
                    java-version: '21'  # 设置 JDK 版本为 21
                    distribution: 'zulu'  # 选择 Zulu 分发版本（其他选项包括 adopt, temurin 等）

            -   name: Run Gradle clean build
                run: ./gradlew clean build  # 执行 Gradle 构建命令

            -   name: Upload build artifacts
                if: success()  # 如果构建成功，上传构建产物
                uses: actions/upload-artifact@v2
                with:
                    name: build-artifact
                    path: build/libs  # 上传构建产物的路径
